### ISSUE TITLE
Train the parser with GPT encoder

### ISSUE THREAD

**Issue by acDante** [princeton-vl/attach-juxtapose-parser#5]
Hi, thanks for your interesting work! I am trying to train your parser using a GPT encoder but got some techincal errors during training. I created a Hydra config file like the following one:

```
# @package _global_
d_model: 2048

encoder: gpt2-medium
use_tags: false
use_words: false
d_kqv: 64
d_ff: 2048
word_emb_dropout: 0.3
tag_emb_dropout: 0
relu_dropout: 0.2
residual_dropout: 0
attention_dropout: 0
num_attn_layers: 4
num_attn_heads: 8

decoder: graph
num_gcn_layers: 4

learning_rate: 3e-5
weight_decay: 0
subbatch_max_tokens: 700
```

Since GPT does not have cls and sep special tokens, I also added these two lines to the constructors in `dataloader.py` and `parser.py`: 

```
special_tokens = {"cls_token":"[CLS]", "sep_token": "[SEP]"}
self.tokenizer.add_special_tokens(special_tokens)       
```

However, during training I got this runtime error  "Assertion 'srcIndex < srcSelectDimSize` failed on GPU " from CUDA. Could you provide any guidance on how to train your model based on GPT?

**Comment by yangky11** [comment]
Thanks for your interest in our work!

I have never experimented with GPT2 in this work, and unfortunately, I'm unable to help with that due to limited bandwidth.
It should be possible in principle, e.g., Kitaev et al. [1] use our work + GPT2. 

[1] Kitaev, Nikita, Thomas Lu, and Dan Klein. "Learned Incremental Representations for Parsing." Proceedings of the 60th Annual Meeting of the Association for Computational Linguistics (Volume 1: Long Papers). 2022.
